*** Variables ***
${REGISTER_NAME_INPUT}          css=[data-testid="nome"]
${REGISTER_EMAIL_INPUT}         css=[data-testid="email"]
${REGISTER_PASSWORD_INPUT}      css=[data-testid="password"]
${REGISTER_ADMIN_CHECKBOX}      css=[data-testid="checkbox"]
${REGISTER_BUTTON}              css=[data-testid="cadastrar"]
${LOGIN_FROM_REGISTER_BUTTON}   css=[data-testid="entrar"]
${REGISTRATION_SUCCESS_MESSAGE}    xpath=//a[contains(@class,'alert-link') and normalize-space()='Cadastro realizado com sucesso']
${REGISTER_EMAIL_EXISTS_MESSAGE}    xpath=//div[contains(@class,'alert')]//span[normalize-space()='Este email já está sendo usado']
${REGISTER_NAME_REQUIRED_MESSAGE}        xpath=//div[contains(@class,'alert')]//span[normalize-space()='Nome é obrigatório']
${REGISTER_EMAIL_REQUIRED_MESSAGE}       xpath=//div[contains(@class,'alert')]//span[normalize-space()='Email é obrigatório']
${REGISTER_PASSWORD_REQUIRED_MESSAGE}   xpath=//div[contains(@class,'alert')]//span[normalize-space()='Password é obrigatório']